sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
addons:
  apt:
    packages:
      - google-chrome-stable
after_success:
  - |
    if [ $TRAVIS_PULL_REQUEST = "false" ]; then
      npm install codecov
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
      npm run sauce
    fi
